os: linux
dist: focal

language: go
go: 1.15.5


install:
  - go mod download
  - go generate

script:
  - go test -v ./...


notifications:
  email:
    recipients:
      - 1586616064@qq.com
    on_success: always
    on_failure: always
